#!/bin/sh
exec 2>&1
mkdir /data 2>/dev/null

PARSE_DB_URL() {
    proto="$(echo $DATABASE_URL | grep '://' | sed -e's,^\(.*://\).*,\1,g')"
    if [[ "${proto}" =~ postgres ]]; then
        export DB_TYPE=postgres
        export DB_SSL_MODE=require
    elif [[ "${proto}" =~ mysql ]]; then
        export DB_TYPE=mysql
        export DB_SSL_MODE=true
    fi

    url=$(echo $DATABASE_URL | sed -e s,${proto},,g)
    userpass="$(echo $url | grep @ | cut -d@ -f1)"
    export DB_PASS=$(echo $userpass | grep : | cut -d: -f2)
    if [ -n "$DB_PASS" ]; then
        export DB_USER=$(echo $userpass | grep : | cut -d: -f1)
    else
        export DB_USER=$userpass
    fi

    hostport=$(echo $url | sed -e s,$userpass@,,g | cut -d/ -f1)
    export DB_PORT=$(echo $hostport | grep : | cut -d: -f2)
    if [ -n "$DB_PORT" ]; then
        export DB_HOST=`echo $hostport | grep : | cut -d: -f1`
    else
        export DB_HOST=$hostport
    fi
    if [[ ${DB_TYPE} = postgres ]] && [[ ${DB_PORT} = "" ]]; then
        export DB_PORT=5432
    fi

    export DB_NAME="`echo $url | grep / | cut -d/ -f2- | sed 's|?.*||'`"
}

if [ "${DATABASE_URL}" != "" ]; then
    PARSE_DB_URL
fi

EXEC=$(head /dev/urandom | md5sum | cut -c 1-9)
ln -sf /usr/bin/alist /usr/bin/${EXEC}
export HTTP_PORT=${PORT}
export TEMP_DIR=/temp
cd /

exec ${EXEC} server --no-prefix
