name: Deploy to Heroku

on:
  workflow_dispatch:
    inputs:
      heroku_app_name:
        description: 'Heroku App Name'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: 5hojib/heroku-deploy-action@v1.0.1
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ inputs.heroku_app_name }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_DATABASE_URL: ${{ secrets.DATABASE_URL }}
