name: release

on:
  release:
    types: [published]

jobs:
  release:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: ['1.20']
    name: Release
    runs-on: ${{ matrix.platform }}
    steps:
      - name: release
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.MY_TOKEN }}
          id: ${{ github.event.release.id }}
          prerelease: true

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo snap install zig --classic --beta
          docker pull crazymax/xgo:latest
          go install github.com/crazy-max/xgo@latest
          sudo apt install upx

      - name: Build
        run: |
          bash build.sh release heroku

      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          files: build/compress/*
          prerelease: false
